name: '${pluginName}'
version: '${version}'
main: '${group}.region.plugin.RegionSurvivalPlugin'
api-version: '${paperVersion}'
libraries:
  - io.github.monun:tap-core:4.9.8
  - io.github.monun:kommand-core:3.1.7
  - io.github.monun:invfx-core:3.3.2